"$schema" = 'https://starship.rs/config-schema.json'

format = """
[█](color_cream)\
$os\
$username\
[](bg:color_tan fg:color_cream)\
$directory\
[](fg:color_tan bg:color_yellow)\
$git_branch\
$git_status\
[](fg:color_yellow bg:color_gray)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_gray bg:color_bg3)\
$docker_context\
$conda\
$pixi\
[](fg:color_bg3 bg:color_bg1)\
$time\
[ ](fg:color_bg1)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_cream  = '#ebdbb2'
color_tan    = '#bdae93'
color_yellow = '#d79921'
color_gray   = '#928374'
color_bg3    = '#665c54'
color_bg2    = '#504945'
color_bg1    = '#3c3836'
color_bg0    = '#282828'
color_green  = '#98971a'
color_red    = '#cc241d'
color_purple = '#b16286'

[os]
disabled = false
style = "bg:color_cream fg:color_bg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰧭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰧨"
Fedora = "󰧛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰧇"
Artix = "󰧇"
EndeavourOS = ""
CentOS = ""
Debian = "󰧚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_cream fg:color_bg0"
style_root = "bg:color_cream fg:color_bg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_bg0 bg:color_tan"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲹 "

[git_branch]
symbol = ""
style = "bg:color_yellow"
format = '[[ $symbol $branch ](fg:color_bg0 bg:color_yellow)]($style)'

[git_status]
style = "bg:color_yellow"
format = '[[($all_status$ahead_behind )](fg:color_bg0 bg:color_yellow)]($style)'

[nodejs]
symbol = ""
style = "bg:color_gray"
format = '[[ $symbol( $version) ](fg:color_bg0 bg:color_gray)]($style)'

[c]
symbol = " "
style = "bg:color_gray"
format = '[[ $symbol( $version) ](fg:color_bg0 bg:color_gray)]($style)'

[cpp]
symbol = " "
style = "bg:color_gray"
format = '[[ $symbol( $version) ](fg:color_bg0 bg:color_gray)]($style)'

[rust]
symbol = ""
style = "bg:color_gray"
format = '[[ $symbol( $version) ](fg:color_bg0 bg:color_gray)]($style)'

[golang]
symbol = ""
style = "bg:color_gray"
format = '[[ $symbol( $version) ](fg:color_bg0 bg:color_gray)]($style)'

[php]
symbol = ""
style = "bg:color_gray"
format = '[[ $symbol( $version) ](fg:color_bg0 bg:color_gray)]($style)'

[java]
symbol = ""
style = "bg:color_gray"
format = '[[ $symbol( $version) ](fg:color_bg0 bg:color_gray)]($style)'

[kotlin]
symbol = ""
style = "bg:color_gray"
format = '[[ $symbol( $version) ](fg:color_bg0 bg:color_gray)]($style)'

[haskell]
symbol = ""
style = "bg:color_gray"
format = '[[ $symbol( $version) ](fg:color_bg0 bg:color_gray)]($style)'

[python]
symbol = ""
style = "bg:color_gray"
format = '[[ $symbol( $version) ](fg:color_bg0 bg:color_gray)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:color_cream bg:color_bg3)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:color_cream bg:color_bg3)]($style)'

[pixi]
style = "bg:color_bg3"
format = '[[ $symbol( $version)( $environment) ](fg:color_cream bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_cream bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:color_green)'
error_symbol = '[❯](bold fg:color_red)'
vimcmd_symbol = '[❮](bold fg:color_green)'
vimcmd_replace_one_symbol = '[❮](bold fg:color_purple)'
vimcmd_replace_symbol = '[❮](bold fg:color_purple)'
vimcmd_visual_symbol = '[❮](bold fg:color_yellow)'
