# vim: ft=tmux

##### --- Base UI --- #####

set -g mode-style "fg=#ebdbb2,bg=#3c3836"
set -g message-style "fg=#ebdbb2,bg=#3c3836"
set -g message-command-style "fg=#ebdbb2,bg=#3c3836"

set -g pane-border-style "fg=#3c3836"
set -g pane-active-border-style "fg=#ebdbb2"

set -g status "on"
set -g status-interval 1
set -g status-justify "left"

set -g status-style "fg=#a89984,bg=#282828"
set -g status-bg "#282828"

set -g status-left-length 100
set -g status-right-length 100
set -g status-left-style NONE
set -g status-right-style NONE

##### --- LEFT (session → user) --- #####

set -g status-left "\
#[fg=#282828,bg=#ebdbb2,bold] #S \
#[fg=#ebdbb2,bg=#bdae93]\
#[fg=#282828,bg=#bdae93,bold] #(whoami) \
#[fg=#bdae93,bg=#282828]\
#[bg=#282828]\
"

##### --- RIGHT (date → time → host) --- #####

set -g status-right "\
#[fg=#282828,bg=#504945]\
#[fg=#ebdbb2,bg=#504945] %d %b %Y \
#[fg=#504945,bg=#665c54]\
#[fg=#ebdbb2,bg=#665c54] %H:%M:%S \
#[fg=#665c54,bg=#928374]\
#[fg=#282828,bg=#928374,bold] #h \
#[fg=#928374,bg=#282828]\
#[bg=#282828]\
"

##### --- WINDOWS --- #####

setw -g window-status-separator ""

# Inactive
setw -g window-status-format "\
#[bg=#282828]\
#[fg=#282828,bg=#3c3836]\
#[fg=#a89984,bg=#3c3836] #I #{b:pane_current_path} \
#[fg=#3c3836,bg=#282828]\
#[bg=#282828]\
"

# Active
setw -g window-status-current-format "\
#[bg=#282828]\
#[fg=#282828,bg=#ebdbb2]\
#[fg=#282828,bg=#ebdbb2,bold] #I \
#[fg=#ebdbb2,bg=#d79921] #{b:pane_current_path} \
#[fg=#d79921,bg=#282828]\
#[bg=#282828]\
"

##### --- Activity --- #####

setw -g window-status-activity-style "underscore,fg=#a89984,bg=#282828"
setw -g window-status-style "NONE,fg=#a89984,bg=#282828"
